services:
  db:
    image: postgres:16
    container_name: lista_compras_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: shoppinglist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"             # no host usa 5433 para evitar conflito; dentro dos containers segue 5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shoppinglist"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./api
    container_name: lista_compras_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/shoppinglist?schema=public
      NODE_ENV: development
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./api:/app
      - api_node_modules:/app/node_modules
    command: >
      sh -c "pnpm install &&
             pnpm prisma:generate &&
             pnpm dev"

volumes:
  db_data:
  api_node_modules:
